// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Represents the table public.sensor_data */
export default interface SensorData {
  time: Date;

  sensor_id: string;

  battery: number | null;

  temperature: number | null;

  dist_z0: number | null;

  dist_z1: number | null;

  dist_z2: number | null;

  dist_z3: number | null;

  dist_z4: number | null;

  dist_z5: number | null;

  dist_z6: number | null;

  dist_z7: number | null;

  dist_z8: number | null;

  dist_z9: number | null;

  dist_z10: number | null;

  dist_z11: number | null;

  dist_z12: number | null;

  dist_z13: number | null;

  dist_z14: number | null;

  dist_z15: number | null;

  status_z0: number | null;

  status_z1: number | null;

  status_z2: number | null;

  status_z3: number | null;

  status_z4: number | null;

  status_z5: number | null;

  status_z6: number | null;

  status_z7: number | null;

  status_z8: number | null;

  status_z9: number | null;

  status_z10: number | null;

  status_z11: number | null;

  status_z12: number | null;

  status_z13: number | null;

  status_z14: number | null;

  status_z15: number | null;
}

/** Represents the initializer for the table public.sensor_data */
export interface SensorDataInitializer {
  time: Date;

  sensor_id: string;

  battery?: number | null;

  temperature?: number | null;

  dist_z0?: number | null;

  dist_z1?: number | null;

  dist_z2?: number | null;

  dist_z3?: number | null;

  dist_z4?: number | null;

  dist_z5?: number | null;

  dist_z6?: number | null;

  dist_z7?: number | null;

  dist_z8?: number | null;

  dist_z9?: number | null;

  dist_z10?: number | null;

  dist_z11?: number | null;

  dist_z12?: number | null;

  dist_z13?: number | null;

  dist_z14?: number | null;

  dist_z15?: number | null;

  status_z0?: number | null;

  status_z1?: number | null;

  status_z2?: number | null;

  status_z3?: number | null;

  status_z4?: number | null;

  status_z5?: number | null;

  status_z6?: number | null;

  status_z7?: number | null;

  status_z8?: number | null;

  status_z9?: number | null;

  status_z10?: number | null;

  status_z11?: number | null;

  status_z12?: number | null;

  status_z13?: number | null;

  status_z14?: number | null;

  status_z15?: number | null;
}

/** Represents the mutator for the table public.sensor_data */
export interface SensorDataMutator {
  time?: Date;

  sensor_id?: string;

  battery?: number | null;

  temperature?: number | null;

  dist_z0?: number | null;

  dist_z1?: number | null;

  dist_z2?: number | null;

  dist_z3?: number | null;

  dist_z4?: number | null;

  dist_z5?: number | null;

  dist_z6?: number | null;

  dist_z7?: number | null;

  dist_z8?: number | null;

  dist_z9?: number | null;

  dist_z10?: number | null;

  dist_z11?: number | null;

  dist_z12?: number | null;

  dist_z13?: number | null;

  dist_z14?: number | null;

  dist_z15?: number | null;

  status_z0?: number | null;

  status_z1?: number | null;

  status_z2?: number | null;

  status_z3?: number | null;

  status_z4?: number | null;

  status_z5?: number | null;

  status_z6?: number | null;

  status_z7?: number | null;

  status_z8?: number | null;

  status_z9?: number | null;

  status_z10?: number | null;

  status_z11?: number | null;

  status_z12?: number | null;

  status_z13?: number | null;

  status_z14?: number | null;

  status_z15?: number | null;
}

/** Zod schema for sensor_data */
export const sensorData = z.object({
  time: z.date(),
  sensor_id: z.string(),
  battery: z.number(),
  temperature: z.number(),
  dist_z0: z.number(),
  dist_z1: z.number(),
  dist_z2: z.number(),
  dist_z3: z.number(),
  dist_z4: z.number(),
  dist_z5: z.number(),
  dist_z6: z.number(),
  dist_z7: z.number(),
  dist_z8: z.number(),
  dist_z9: z.number(),
  dist_z10: z.number(),
  dist_z11: z.number(),
  dist_z12: z.number(),
  dist_z13: z.number(),
  dist_z14: z.number(),
  dist_z15: z.number(),
  status_z0: z.number(),
  status_z1: z.number(),
  status_z2: z.number(),
  status_z3: z.number(),
  status_z4: z.number(),
  status_z5: z.number(),
  status_z6: z.number(),
  status_z7: z.number(),
  status_z8: z.number(),
  status_z9: z.number(),
  status_z10: z.number(),
  status_z11: z.number(),
  status_z12: z.number(),
  status_z13: z.number(),
  status_z14: z.number(),
  status_z15: z.number(),
});
