// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Represents the table public.company */
export default interface Company {
  symbol: string;

  name: string;
}

/** Represents the initializer for the table public.company */
export interface CompanyInitializer {
  symbol: string;

  name: string;
}

/** Represents the mutator for the table public.company */
export interface CompanyMutator {
  symbol?: string;

  name?: string;
}

/** Zod schema for company */
export const company = z.object({
  symbol: z.string(),
  name: z.string(),
});
