// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { Knex } from 'knex';
import type { default as Company, CompanyInitializer, CompanyMutator } from './public/Company';
import type { default as Conditions, ConditionsInitializer, ConditionsMutator } from './public/Conditions';
import type { default as SensorData, SensorDataInitializer, SensorDataMutator } from './public/SensorData';
import type { default as StocksRealTime, StocksRealTimeInitializer, StocksRealTimeMutator } from './public/StocksRealTime';
import type { default as Hyper11Chunk, Hyper11ChunkInitializer, Hyper11ChunkMutator } from './_timescaledb_internal/Hyper11Chunk';
import type { default as Hyper22Chunk, Hyper22ChunkInitializer, Hyper22ChunkMutator } from './_timescaledb_internal/Hyper22Chunk';
import type { default as Hyper23Chunk, Hyper23ChunkInitializer, Hyper23ChunkMutator } from './_timescaledb_internal/Hyper23Chunk';
import type { default as Hyper24Chunk, Hyper24ChunkInitializer, Hyper24ChunkMutator } from './_timescaledb_internal/Hyper24Chunk';
import type { default as Hyper25Chunk, Hyper25ChunkInitializer, Hyper25ChunkMutator } from './_timescaledb_internal/Hyper25Chunk';
import type { default as Hyper36Chunk, Hyper36ChunkInitializer, Hyper36ChunkMutator } from './_timescaledb_internal/Hyper36Chunk';

declare module 'knex/types/tables' {
  interface Tables {
    'company': Knex.CompositeTableType<Company, CompanyInitializer, CompanyMutator>;
    'conditions': Knex.CompositeTableType<Conditions, ConditionsInitializer, ConditionsMutator>;
    'sensor_data': Knex.CompositeTableType<SensorData, SensorDataInitializer, SensorDataMutator>;
    'stocks_real_time': Knex.CompositeTableType<StocksRealTime, StocksRealTimeInitializer, StocksRealTimeMutator>;
    '_hyper_1_1_chunk': Knex.CompositeTableType<Hyper11Chunk, Hyper11ChunkInitializer, Hyper11ChunkMutator>;
    '_hyper_2_2_chunk': Knex.CompositeTableType<Hyper22Chunk, Hyper22ChunkInitializer, Hyper22ChunkMutator>;
    '_hyper_2_3_chunk': Knex.CompositeTableType<Hyper23Chunk, Hyper23ChunkInitializer, Hyper23ChunkMutator>;
    '_hyper_2_4_chunk': Knex.CompositeTableType<Hyper24Chunk, Hyper24ChunkInitializer, Hyper24ChunkMutator>;
    '_hyper_2_5_chunk': Knex.CompositeTableType<Hyper25Chunk, Hyper25ChunkInitializer, Hyper25ChunkMutator>;
    '_hyper_3_6_chunk': Knex.CompositeTableType<Hyper36Chunk, Hyper36ChunkInitializer, Hyper36ChunkMutator>;
  }
}
