// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Represents the table _timescaledb_internal._hyper_1_1_chunk */
export default interface Hyper11Chunk {
  time: Date;

  location: string;

  temperature: number | null;
}

/** Represents the initializer for the table _timescaledb_internal._hyper_1_1_chunk */
export interface Hyper11ChunkInitializer {
  time: Date;

  location: string;

  temperature?: number | null;
}

/** Represents the mutator for the table _timescaledb_internal._hyper_1_1_chunk */
export interface Hyper11ChunkMutator {
  time?: Date;

  location?: string;

  temperature?: number | null;
}

/** Zod schema for _hyper_1_1_chunk */
export const hyper11Chunk = z.object({
  time: z.date(),
  location: z.string(),
  temperature: z.number(),
});
