// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Represents the table public.conditions */
export default interface Conditions {
  time: Date;

  location: string;

  temperature: number | null;
}

/** Represents the initializer for the table public.conditions */
export interface ConditionsInitializer {
  time: Date;

  location: string;

  temperature?: number | null;
}

/** Represents the mutator for the table public.conditions */
export interface ConditionsMutator {
  time?: Date;

  location?: string;

  temperature?: number | null;
}

/** Zod schema for conditions */
export const conditions = z.object({
  time: z.date(),
  location: z.string(),
  temperature: z.number(),
});
