// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Represents the table public.stocks_real_time */
export default interface StocksRealTime {
  time: Date;

  symbol: string;

  price: number | null;

  day_volume: number | null;
}

/** Represents the initializer for the table public.stocks_real_time */
export interface StocksRealTimeInitializer {
  time: Date;

  symbol: string;

  price?: number | null;

  day_volume?: number | null;
}

/** Represents the mutator for the table public.stocks_real_time */
export interface StocksRealTimeMutator {
  time?: Date;

  symbol?: string;

  price?: number | null;

  day_volume?: number | null;
}

/** Zod schema for stocks_real_time */
export const stocksRealTime = z.object({
  time: z.date(),
  symbol: z.string(),
  price: z.number(),
  day_volume: z.number(),
});
